# Setup
title:        A-Town
tagline:      Two Dudes From Arnold
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Author name
  url:        http://yourhomepage.com 

# Gems
plugins:
  - jekyll-paginate

#Others
markdown: kramdown
fbcomments: yes